version: '3.8'

services:
  spotify-dash:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: spotify-dash-app
    ports:
      - "8050:8050"
    environment:
      - PYTHONPATH=/app
      - DASH_DEBUG_MODE=False
    volumes:
      # Uncomment next line for development with live reload
      # - ./src:/app
      - ./src/assets:/app/assets:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s